name = "aof25"
version = "0.1.0"
license = "MIT"
author = "Chris Dawes"
maintainer = "cmsd2@cantab.net"
copyright = "Copyright 2026, Chris Dawes"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
